name: Lint and test workflow
on:
  push:
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install non-python dependencies
        run: |
          sudo apt-get install -y graphviz-dev

      - name: Setup Python environment
        uses: ./.github/actions/action-setup_task-installPyProject
        with:
          python-version: "3.10"

      - name: isort
        run: uv run isort mri_degad/*.py -c

      - name: Black
        run: uv run black mri_degad --check

      - name: snakefmt
        run: uv run snakefmt mri_degad --check

  test:
    runs-on: ubuntu-latest
    needs: ["quality"]
    strategy:
      matrix:
        python-version: ["3.10","3.11","3.12"]

    steps:
      - name: Install non-python dependencies
        run: |
          sudo apt-get install -y graphviz-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python environments
        uses: ./.github/actions/action-setup_task-installPyProject
        with:
          python-version: ${{ matrix.python-version }}
          install-library: true

      - name: Setup env for mri_degad
        run: |
          echo "MRI_DEGAD_CACHE_DIR=`pwd`/tests/data/mri_degad_cache_dir" >> $GITHUB_ENV

      - name: Test single T1w bids
        run: |
          uv run mri_degad tests/data/ test_out participant -np --skull-strip -c all